name: AtCoder Rating Notifier

on:
  # JSTの土曜日と日曜日の23:00から翌1:00まで、5分おきに実行
  # UTCでは 14:00 から 16:00 (土曜: 6, 日曜: 0)
  schedule:
    - cron: '*/5 14-16 * * 6,0'
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    # タイムアウト設定（例: 5分）
    timeout-minutes: 5

    # GitHubのSecretsとVariablesを環境変数として設定
    env:
      ATCODER_USER_ID: ${{ vars.ATCODER_USER_ID }}
      DISCORD_WEBHOOK_URLS_NOTIFIER: ${{ secrets.DISCORD_WEBHOOK_URLS_NOTIFIER }}

    steps:
      # ステップ1: リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # ステップ2: Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ステップ3: 状態ファイルをキャッシュから復元・保存
      - name: Cache state files
        uses: actions/cache@v4
        id: cache-state
        with:
          path: |
            last_contest.txt
            notified_today.txt
          key: ${{ runner.os }}-atcoder-state-${{ env.ATCODER_USER_ID }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-atcoder-state-${{ env.ATCODER_USER_ID }}-

      # ステップ4: Pythonの依存パッケージをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ステップ5: 通知スクリプトを実行
      - name: Run notifier script
        run: |
          echo "現在時刻 (JST): $(TZ='Asia/Tokyo' date)"
          python notifier.py

      # ステップ6: キャッシュを強制保存（ファイルを変更して確実に保存）
      - name: Force cache save
        run: |
          echo "$(date)" >> last_contest.txt.timestamp
          echo "$(date)" >> notified_today.txt.timestamp
        if: always()