name: AtCoder Rating Notifier

on:
  # 土・日の22:00-翌1:45 (JST) ごろに15分ごとに実行
  schedule:
    - cron: '*/15 13-16 * * 6,0'

  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 状態ファイル (latest_contest.txt) をキャッシュから復元
      - name: Restore state from cache
        uses: actions/cache@v4
        with:
          path: latest_contest.txt
          key: ${{ runner.os }}-atcoder-state-${{ secrets.ATCODER_USER_ID }}

      # 3. Pythonの環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 4. 必要なライブラリをインストール
      - name: Install dependencies
        run: pip install requests

      # 5. Pythonスクリプトを実行
      # スクリプトはキャッシュから復元された latest_contest.txt を読み書きする
      - name: Run script
        env:
          ATCODER_USER_ID: ${{ secrets.ATCODER_USER_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py